### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by b-t-k** [PiperKev/edgar-rice-burroughs_the-mucker#1]
- Run semanticate again and then fix the `<em>`’s in 1-2 and 1-12
- Run modernize-spelling again

## content.opf
-long description. I don’t understand why *Return of The Mucker* would be italicized if it was a story in _All-Story Weekly_
## chapter-2-4
- naïvely -> naively (run modernize spelling)
## chapter-2-12
- a question… do you think the italics in “*Si*, senorita,” are because its Spanish or because its emphasized? (Again in **2-14**, **2-15**)
## chapter 2-17
- live stock -> livestock

**Comment by PiperKev** [comment]
Reran semanticate and modernize-spelling and fixed resulting issues.

Put "The Mucker" and "Return of The Mucker" magazine stories in quotation marks.

**Comment by b-t-k** [comment]
You didn't push the change to the quotes in in the opf file...

**Comment by PiperKev** [comment]
I was just seeing if you were paying attention!  That's my story, and I'm sticking with it... :-)

Done!

And are you okay with my explanation for "Si"?

**Comment by b-t-k** [comment]
Ya, that's fine. I just think it was weird even the original had "Si" in italics but senor/senorita in roman.
